export async function seed(knex) {
  await knex('users').insert([
    {
      name: 'Thorgar',
      auth0_sub: '1',
      last_name: 'Frostpeak',
      email: 'troll1@gmail.com',
      picture: '',
      active_bridge: 'Onehunga Harbour Road Bridge',
      fav_bridges: 'Onepoto Bridge',
      total_toll: 86,
    },

    {
      name: 'Berga',
      auth0_sub: '2',
      last_name: 'Fluntfist',
      email: 'troll2@gmail.com',
      picture: '',
      active_bridge: 'Auckland Harbour Bridge',
      total_toll: 122,
    },

    {
      name: 'Roknar',
      auth0_sub: '3',
      last_name: 'Rockridge',
      email: 'troll3@gmail.com',
      picture: '',
      active_bridge: 'Jacobs Ladder Bridge',
      total_toll: 40,
    },
    {
      name: 'Cragspine',
      auth0_sub: '4',
      last_name: 'Morndul',
      email: 'troll4@gmail.com',
      picture: '',
      active_bridge: 'Tamaki Bridge',

      total_toll: 250,
    },
    {
      name: 'ledgefoot',
      auth0_sub: '5',
      last_name: 'Mountainmaw',
      email: 'troll5@gmail.com',
      picture: '',
      active_bridge: 'Victoria Park Viaduct',
      total_toll: 100,
    },

    {
      name: 'Ledgefoot',
      auth0_sub: '6',
      last_name: 'Iceshard',
      email: 'troll6@gmail.com',
      picture: '',
      active_bridge: 'Newmarket Viaduct',
      total_toll: 120,
    },
    {
      name: 'SnowMantle',
      auth0_sub: '7',
      last_name: 'Mountainmaw',
      email: 'troll7@gmail.com',
      picture: '',
      active_bridge: 'Māngere Bridge',
      total_toll: 10,
    },

    {
      name: 'Terragar',
      auth0_sub: '8',
      last_name: 'Cragtooth',
      email: 'troll8@gmail.com',
      picture: '',
      active_bridge: 'Panmure Bridge',
      total_toll: 90,
    },
    {
      name: 'Bouldershoulder',
      auth0_sub: '9',
      last_name: 'GravelFoot',
      email: 'troll10@gmail.com',
      picture: '',
      active_bridge: 'Wynyard Crossing',
      total_toll: 110,
    },

    {
      name: 'Mounta',
      auth0_sub: '10',
      last_name: 'Frostpeak',
      email: 'troll10@gmail.com',
      picture: '',
      active_bridge: 'Wynyard Crossing',
      total_toll: 175,
    },

    {
      name: 'Skarn',
      auth0_sub: '11',
      last_name: 'Tundar',
      email: 'troll11@gmail.com',
      picture: '',
      active_bridge: 'Upper Harbour Bridge',
      total_toll: 175,
    },
    {
      name: 'Slatefist',
      auth0_sub: '12',
      last_name: 'Terra',
      email: 'troll12@gmail.com',
      picture: '',
      active_bridge: 'Newmarket Viaduct',
      total_toll: 185,
    },

    {
      name: 'Stoneclaw',
      auth0_sub: '13',
      last_name: 'Frostpeak',
      email: 'troll13@gmail.com',
      picture: '',
      active_bridge: 'Upper Harbour Bridge',
      total_toll: 135,
    },
    {
      name: 'Cliffsnout',
      auth0_sub: '14',
      last_name: 'Cliffsnout',
      email: 'troll14@gmail.com',
      picture: '',
      active_bridge: 'Grafton Bridge',
      total_toll: 200,
    },

    {
      name: 'Highcrag',
      auth0_sub: '15',
      last_name: 'woodpeak',
      email: 'troll15@gmail.com',
      picture: '',
      total_toll: 175,
    },
  ])
}
